services:
  reception:
    container_name: reception_web

    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        RECEPTION_API_URL: ${RECEPTION_API_URL}

    env_file:
      - .env.docker

    ports:
      - "3000:3000"

    restart: unless-stopped

